from setuptools import setup, find_packages

setup(
    name="voicevault",
    version="1.0.0",
    packages=find_packages(),
    install_requires=[
        "numpy>=1.20.0",
        "scipy>=1.7.0",
        "librosa>=0.8.1",
        "soundfile>=0.10.3",
        "tensorflow>=2.8.0",
        "torch>=1.10.0",
        "pandas>=1.3.0",
        "matplotlib>=3.4.0",
        "pyyaml>=6.0",
        "pyaudio>=0.2.11",
        "scikit-learn>=1.0.0",
        "numba>=0.54.0",
        "resampy>=0.2.2",
        "pesq>=0.0.3",
        "pystoi>=0.3.3",
        "praat-parselmouth>=0.4.2",
        "acoustics>=0.2.3",
        "gputil>=0.0.1",
        "ray>=2.0.0",
    ],  
    author="VoiceVault Team",
    author_email="contact@voicevault.ai",
    description="State-of-the-Art Voice Processing Pipeline",
)
